language: php

php:
    - 7.1
    - 7.0
    - 5.6
    - hhvm

before_script:
    - composer install
    - mysql -e 'create database mydb;'
    - php vendor/bin/phinx migrate -c vendor/infuse/auth/phinx.yml

script:
    - mkdir -p build/logs
    - phpunit

after_script:
    - vendor/bin/coveralls